### ISSUE TITLE
代码块显示不正常怎么回事？

### ISSUE THREAD

**Issue by wudihechao** [honjun/hexo-theme-sakura#35]
为什么代码每一行是单独额一个代码块？

![codebug](https://user-images.githubusercontent.com/54797430/70036782-68095d80-15f0-11ea-8b5d-50fcaeae506e.png)

[https://hewanyue.com/blog/f989902e.html](https://hewanyue.com/blog/f989902e.html)

**Comment by KaizynX** [comment]
同问代码渲染出现问题
![image](https://user-images.githubusercontent.com/35752703/77037494-7424f980-69ec-11ea-8742-69066a23dc29.png)

**Comment by KaizynX** [comment]
我的问题解决了，问题在于根目录下的 `_config.yml` 文件

```yml
highlight: 
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:
```

上面三个选项我之前全写了 `true`
